Add messages on StopArea tap
OPENER-next/OpenStop pull request #100
Opened 2022-09-07 07:41 UTC by 7h30n3

Add messages on StopArea tap in case of:

- Connection Timeout
- Unknown Error
- All Questions answered

2022-09-12 08:13 UTC, Robbendebiene requested changes

2022-09-12 08:13 UTC, Robbendebiene commented on lib/view_models/osm_elements_provider.dart
> +  Future<void> loadElementsFromStopArea(StopArea stopArea) async {
I think we also need to remove the `catch` in this function, otherwise timeout exceptions will be suppressed.
However best practice would be if this function (or any API function below) internally makes all the error checks and returns custom exceptions, so any "outside" code can be written like this:


```dart
try {
  await osmElementProvider.loadElementsFromStopArea(stopArea);
  if (osmElementProvider.extractedOsmElementsMap[stopArea]!.isEmpty) {
    scaffold.showSnackBar(
      CustomSnackBar('Alle Fragen bereits beantwortet.')
    );
  }
}
on ExampleConnectionTimeout {
  scaffold.showSnackBar(
    CustomSnackBar('Fehler: Zeitüberschreitung bei der Server-Abfrage.')
  );
}
on OtherExampleException {
  scaffold.showSnackBar(
    CustomSnackBar('Fehler: Zeitüberschreitung bei der Server-Abfrage.')
  );
}
catch(e) {
  scaffold.showSnackBar(
    CustomSnackBar('Unbekannter Fehler bei der Server-Abfrage.')
  );
}
```

Alternatively I would add an else to the DioError catch:

```dart
   on DioError catch (e) {
      if (e.type == DioErrorType.connectTimeout) {
        scaffold.showSnackBar(
            CustomSnackBar('Fehler: Zeitüberschreitung bei der Server-Abfrage.')
        );
      }
      else {
        scaffold.showSnackBar(
            CustomSnackBar('Unbekannter Fehler bei der Server-Abfrage.')
        );
      }
    }
    catch(e) {
      debugPrint(e.toString());
      scaffold.showSnackBar(
          CustomSnackBar('Ein Unbekannter Fehler ist aufgetreten.')
      );
    }
```

2022-09-12 08:13 UTC, Robbendebiene commented on lib/screens/home.dart
> +        );
Minor formatting: space after `finally` and indention for `CustomSnackBar`

2022-09-19 14:27 UTC, 7h30n3 commented on lib/screens/home.dart
> +        );
Because I changed the postion of the if-condition the `finally` was removed.

2022-09-20 11:49 UTC, Robbendebiene reviewed
Looks good, I would probably just remove the inner catch with the debug print.

2022-09-20 11:49 UTC, Robbendebiene commented on lib/view_models/osm_elements_provider.dart
> +        rethrow;
If the reason for keeping this catch is because you want to keep this debug print then we should probably remove the other debug print here:

```dart
   catch(e) {
      debugPrint(e.toString());
      scaffold.showSnackBar(
          CustomSnackBar('Unbekannter Fehler.')
      );
    }
```

Otherwise the same error is printed twice.
Strictly speaking the print from the above code catches/prints even more errors than the other one, so they are  not truly identical but almost.

2022-09-20 11:49 UTC, 7h30n3 commented on lib/view_models/osm_elements_provider.dart
> +  Future<void> loadElementsFromStopArea(StopArea stopArea) async {
I implemented the 2nd alternative.

2022-09-20 12:38 UTC, 7h30n3 commented on lib/view_models/osm_elements_provider.dart
> +        rethrow;
I noticed that too, after the commit.
Changed it.

2022-09-20 12:41 UTC, merged