Replace nvbw images with CC0 images
OPENER-next/OpenStop pull request #168
Opened 2023-04-27 20:53 UTC by wielandb

This PR will replace all images in the directory /dependencies/nvbw_open_data/images with images that I took myself and put under the CC0 license.

2023-04-27 20:59 UTC, wielandb commented
At this point, 18 images remain to be replaced.

2023-04-27 22:38 UTC, wielandb commented
At this point, 17 images remain to be replaced

2023-04-28 12:00 UTC, wielandb commented
At this point, 4 images remain to be replaced.

2023-04-28 14:56 UTC, Robbendebiene requested changes
- [ ] Please change all image names to a meaningful name like: "parking_surface" "parking_wheelchair_1".
- [ ] Generally reduce the saturation of the images.
- [ ] Ensure minimal resolution of 1000x1000 and a maximal resolution of 2000x2000

2023-04-28 14:56 UTC, Robbendebiene commented on assets/images/questions/1051b.jpg
If possible an image with less surroundings would be preferred. Alternatively you can crop the image if the resolution allows it.

2023-04-28 14:56 UTC, Robbendebiene commented on assets/images/questions/1051c.jpg
An image similar to this without a car in the front (instead maybe a parking sign) would be preferable.

2023-04-28 14:56 UTC, Robbendebiene commented on assets/images/questions/1051d.jpg
Please align the image

2023-04-28 14:56 UTC, Robbendebiene commented on assets/images/questions/1051g.jpg
Crop image left & right or use a similar image in portrait mode.

2023-04-28 14:56 UTC, Robbendebiene commented on assets/images/questions/1052d.jpg
Can be deleted since we are not using it (yet)

2023-04-28 14:56 UTC, Robbendebiene commented on assets/images/questions/1120a.jpg
We support the idea, but the big blurred chunk of people doesn't look right to us. Please try to find an alternative.

2023-04-28 14:56 UTC, Robbendebiene commented on assets/datasets/question_catalog.json
>              "packages/nvbw_open_data/photos/1120c.jpg",
Reuse `assets/images/questions/1120c.jpg`

2023-04-28 14:56 UTC, Robbendebiene commented on assets/images/questions/1140a.jpg
Please align image horizontally.

2023-04-28 15:43 UTC, wielandb commented on assets/images/questions/1120a.jpg
Would retaking the photo without people in it be sufficient?

2023-04-28 15:45 UTC, wielandb commented on assets/images/questions/1051d.jpg
I am not really sure what is meant by that.

2023-05-05 12:10 UTC, wielandb commented on assets/images/questions/parking_street_side.jpg
Crop bottom

2023-05-05 12:12 UTC, wielandb commented on assets/images/questions/parking_multistorey_2.jpg
Use this image for multi storey

2023-05-05 12:12 UTC, wielandb commented on assets/images/questions/handrail_2.jpg
Reduce saturation/contrast further

2023-05-05 12:13 UTC, wielandb commented on assets/images/questions/IMG_20230505_125425.jpg
Remove

2023-05-05 12:20 UTC, wielandb commented on assets/images/questions/park_and_ride.jpg
Reduce saturation and contrast

2023-05-05 12:42 UTC, Robbendebiene commented on assets/datasets/question_catalog.json
> +			"assets/images/questions/traffic_sign_314_1044-10.png",
Please fix indention (convert tabs to spaces)

2023-05-08 08:46 UTC, 7h30n3 commented on assets/datasets/question_catalog.json
> +            "assets/images/questions/wheelchair_lift_1.jpg"
A picture of a lift shouldn't be attached to a question about a ramp.

2023-05-08 08:48 UTC, 7h30n3 commented on pubspec.yaml
> -
Please restore the empty line.

2023-05-09 11:26 UTC, wielandb commented on assets/datasets/question_catalog.json
> +            "assets/images/questions/wheelchair_lift_1.jpg"
Renamed image to wheelchair_ramp_1 for more clairity

2023-05-09 11:38 UTC, wielandb commented
> * [ ]  Ensure minimal resolution of 1000x1000 and a maximal resolution of 2000x2000

At the moment, the following images violate this rule:

- [ ] approach_aid_no.jpg (too big!)
- [ ] automatic_door_button.jpg (too big!)
- [ ] disabled_parking_1.jpg (too small!)
- [ ] disabled_parking_2.jpg (too small!)
- [ ] disabled_parking_3.jpg (too small!)
- [ ] handrail_2.jpg (too small!)
- [ ] handrail_tactile_writing_1.jpg (too big!)
- [ ] handrail_tactile_writing_2.jpg (too big!)
- [ ] kerb_flush.jpg (too big!)

2023-05-26 14:33 UTC, 7h30n3 commented
The only two things missing are a new image for streetside parking and checking if all images are numbered correctly.

2023-06-02 13:10 UTC, wielandb commented
Should be ready for final review now. :)

2023-06-05 07:55 UTC, merged