Implementation of localizations for the question catalog
OPENER-next/OpenStop pull request #189
Opened 2023-07-11 13:14 UTC by yulieth9109

2023-07-17 07:02 UTC, Robbendebiene commented on lib/main.dart
> +import 'dart:ui' as ui;
Is this namespace necessary to prevent any collision?

2023-07-17 07:03 UTC, Robbendebiene commented on lib/models/question_catalog/question_catalog_reader.dart
> +  final String defaultLocate;
Still contains a typo

2023-07-17 07:04 UTC, Robbendebiene commented on lib/models/question_catalog/question_catalog_reader.dart
> +  late Locale deviceLocale;
Should be removed as it is never used.

2023-07-17 07:08 UTC, Robbendebiene commented on lib/models/question_catalog/question_catalog_reader.dart
> +      return json.decode(utf8.decode(jsonData.buffer.asUint8List()), reviver: reviver);
can be simplified to
```
      final jsonData = await rootBundle.loadString(path);
      return json.decode(jsonData, reviver: reviver);
```

Under the hood it does the same as the previous code.

2023-07-17 07:11 UTC, Robbendebiene commented on lib/models/question_catalog/question_catalog_reader.dart
> +  Future<dynamic> _readFile(String path,
Return a more explicit type:  `Future<Map<String, dynamic>>` (will probably require cast in the functions return statement)

2023-07-18 13:06 UTC, yulieth9109 commented on lib/models/question_catalog/question_catalog_reader.dart
> +      return json.decode(utf8.decode(jsonData.buffer.asUint8List()), reviver: reviver);
I got the error "The argument type 'ByteData' can't be assigned to the parameter type 'String'.dart[argument_type_not_assignable](https://dart.dev/diagnostics/argument_type_not_assignable)" that is why I included the decoding

2023-07-19 07:56 UTC, Robbendebiene commented on lib/models/question_catalog/question_catalog_reader.dart
> +      return json.decode(utf8.decode(jsonData.buffer.asUint8List()), reviver: reviver);
Are you sure that you used the load**String**(path) function?

2023-07-19 15:10 UTC, yulieth9109 commented on lib/models/question_catalog/question_catalog_reader.dart
> +  Future<dynamic> _readFile(String path,
I did the chance and it did not work since the method  _readFile is generic and I used it to read the definition.json I can not return the map casting because it will become a list that I can not read in the reviver function.

2023-08-28 08:20 UTC, Robbendebiene requested changes
- [This](https://github.com/OPENER-next/OpenStop/blob/master/assets/datasets/question_catalog_schema.json#L272-L277) can be removed in this PR.
- Replace `question_catalog.json` with `definition.json` [here](https://github.com/OPENER-next/OpenStop/blob/master/.github/workflows/json_validation.yml) and adjust [this path](https://github.com/OPENER-next/OpenStop/blob/master/.github/workflows/json_validation.yml#L38).
- Address the code validation checks: https://github.com/OPENER-next/OpenStop/actions/runs/5974992411/job/16210125991

2023-08-28 08:20 UTC, Robbendebiene commented on test/parse_json_test.dart
>    });
Remove entire setup function and `late QuestionCatalog questionCatalog;`

Add the following to the start of the test function.

```dart
final questionCatalogReader = QuestionCatalogReader(
  assetPaths: ['assets/question_catalog'],
);
final questionCatalog = questionCatalogReader.questionCatalog.first;
```

2023-08-28 08:20 UTC, Robbendebiene commented on lib/models/questionnaire.dart
> +  }
Please fix indentation.

2023-08-28 08:20 UTC, Robbendebiene commented on lib/models/question_catalog/question_catalog_reader.dart
> +
Please refine the comments and also transform them to "documentation" comments.

2023-08-31 05:59 UTC, yulieth9109 commented on lib/api/app_worker/question_catalog_handler.dart
> +import 'package:flutter/material.dart';
Yes, it was included because the @mustCallSuper. Can be replaced with import 'package:flutter/foundation.dart';

2023-08-31 06:11 UTC, yulieth9109 commented on lib/main.dart
> +import 'models/question_catalog/question_catalog_reader.dart';
When I use "import 'package:open_stop/models/question_catalog/question_catalog.dart';" i get the message "Use relative imports for files in the 'lib' directory.
Try converting the URI to a relative URI.".

2023-08-31 09:09 UTC, Robbendebiene commented on lib/models/question_catalog/question_catalog.dart
> +  QuestionCatalogChange.derive(this.catalog, this.change);
These 2 lines can be removed.

2023-08-31 09:09 UTC, Robbendebiene commented on lib/models/question_catalog/question_catalog.dart
> +  QuestionCatalogChange({
can be a const constructor (add `const` keyword before class)

2023-08-31 10:03 UTC, Robbendebiene commented on .github/workflows/json_validation.yml
> +      - '**/advanced_question_catalog/definition.json'
Just combine the catalog lines to: `- '**/definition.json'` This way any `definition.json` file will be watched regarding of its directory.

2023-08-31 10:04 UTC, Robbendebiene commented on assets/datasets/question_catalog_schema.json
> -
This part should not be deleted

2023-08-31 10:06 UTC, Robbendebiene commented on lib/main.dart
> +import 'models/question_catalog/question_catalog_reader.dart';
Use `import '/models/question_catalog/question_catalog_reader.dart';`

2023-08-31 14:21 UTC, yulieth9109 commented
The changes were implemented

2023-09-01 09:54 UTC, Robbendebiene commented on lib/main.dart
> +      .registerSingleton<AppWorkerInterface>(futures[0] as AppWorkerInterface);
Note the trailing comma. It will ensure that your formatter will format it the same way.

2023-09-01 11:38 UTC, Robbendebiene approved these changes
Thanks, this can finally be merged 🥳

2023-09-01 11:42 UTC, merged