Shimmer effect
OPENER-next/OpenStop pull request #230
Opened 2024-01-08 07:08 UTC by yulieth9109

2024-01-08 11:06 UTC, Robbendebiene requested changes

2024-01-08 11:06 UTC, Robbendebiene commented on lib/widgets/map_overlay/shimmer.dart
> +    required this.child,
You can supply a [SizedBox.expand](https://api.flutter.dev/flutter/widgets/SizedBox/SizedBox.expand.html) as the default value and therefore drop the necessity of passing
```dart
                      child: Container(
                        color: Colors.transparent,
                        width: MediaQuery.of(context).size.width, 
                        height: MediaQuery.of(context).size.height,
                      ),
```

Perhaps alternatively you can even make it nullable (and basically have `null` as default value) since ShaderMask doesn't require a child. You just need to make sure to use a `Positioned.fill` in the stack later. (this would be my preferred solution)

2024-01-08 11:06 UTC, Robbendebiene commented on lib/screens/home.dart
> +                  ),
I think it makes sense to directly include the ignore pointer in the `Shimmer` widget.

Also please move this to the `map_overlay.dart` file making sure it is below the other overlay widgets like buttons and credits text.

2024-01-09 08:57 UTC, yulieth9109 commented on lib/widgets/map_overlay/shimmer.dart
> +    required this.child,
I tried both ways and the shimmer was not painting in any way, then I still left the container.

2024-01-09 08:58 UTC, yulieth9109 commented on lib/screens/home.dart
> +                  ),
I left it in the home.dart because in the map_overlay.dart the shimmer does not cover the complete screen from left to right since it will be painted with a kind of border

2024-01-10 01:13 UTC, yulieth9109 commented
Hi, the recordings are more than 10MB, I create a temporal link to share the videos with you to [download](https://wetransfer.com/downloads/5e791fa76d7108481658886e3d02abb420240110010820/3247ff?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05)

2024-01-31 11:52 UTC, closed without merging

2024-01-31 11:52 UTC, Robbendebiene commented
We are closing this issue in favor of #235