Gallery viewer for additional information
OPENER-next/OpenStop pull request #238
Opened 2024-01-29 19:44 UTC by yulieth9109

2024-02-09 13:41 UTC, Robbendebiene requested changes
One thing that is harder to solve is that the hero transition image is overlaying the arrows that are fading in. When the image gets removed the arrows suddenly appear.

This can only be solved with https://api.flutter.dev/flutter/widgets/Hero/flightShuttleBuilder.html but please do this last after everything else is done and in a separate commit.

2024-02-09 14:47 UTC, Robbendebiene commented on lib/widgets/gallery_viewer.dart
> +      curve: Curves.easeInOut,
```suggestion
      curve: Curves.easeInOutCubicEmphasized,
```

2024-02-09 14:47 UTC, Robbendebiene commented on lib/widgets/gallery_viewer.dart
> +      curve: Curves.easeInOut,
```suggestion
      curve: Curves.easeInOutCubicEmphasized,
```

2024-02-09 14:47 UTC, Robbendebiene commented on lib/widgets/gallery_viewer.dart
> +              scrollBehavior: const ScrollBehavior().copyWith(overscroll: false),
```suggestion

```

2024-02-09 14:47 UTC, Robbendebiene commented on lib/widgets/gallery_viewer.dart
> +              physics: const ClampingScrollPhysics(),
```suggestion

```

2024-02-09 16:01 UTC, Robbendebiene commented
What also doesn't work well is zooming and panning in the image. Most of the time the PageView gesture wins while I think the opposite would be better (InterActiveViewer wins, and only looses when panning isn't possible any more).

Just try zooming in via pinch gesture.

2024-02-10 22:45 UTC, yulieth9109 commented on lib/widgets/gallery_viewer.dart
> +            tag: tag,
I did that and when the user interacts with the Gallery navigation through the images once the Viewer is closed each Hero that was visualized animates. For example, the user visualizes three images then when the viewer is closed three of them animate to the small image

2024-02-11 22:57 UTC, yulieth9109 commented on lib/widgets/gallery_viewer.dart
> +    );
@Robbendebiene could you provide what you expect with this implementation? Are the arrows animated any time the user is scrolling the images, or the animation is when the arrow should disappear?

2024-02-12 12:37 UTC, Robbendebiene commented on lib/widgets/gallery_viewer.dart
> +    );
So the idea is basically that the arrows fade in/out at the last/first page. But the animation is directly bound to the page controller which means slightly dragging from the last page to the previous page will also slightly start to show the right arrow.
You need to do some minor math calculations so the animation values only change from 0 to 1 whenever the first/last page is reached.

2024-02-12 12:47 UTC, Robbendebiene commented on lib/widgets/gallery_viewer.dart
> +            tag: tag,
Good catch. You may be able to mitigate this by destroying the pages out of view.

You could try wrapping the items of the PageView with https://api.flutter.dev/flutter/widgets/KeepAlive-class.html setting it to false

Or using https://api.flutter.dev/flutter/widgets/PageView/PageView.custom.html with a custom delegate.

2024-02-14 10:44 UTC, Robbendebiene commented on lib/widgets/gallery_viewer.dart
> +    );
```dart
class DerivedAnimation<T extends ChangeNotifier> extends Animation<V> {
  final T _notifier;
  final V Function(T) _transformer;

  _ValueListenableDelegateAnimation({
    required T notifier,
    required V Function(T) transformer,
  }) : 
  _notifier = notifier;
  _transformer = transformer;

  @override
  void addListener(VoidCallback listener) {
    _notifier.addListener(listener);
  }

  @override
  void addStatusListener(AnimationStatusListener listener) {
    // status will never change.
  }

  @override
  void removeListener(VoidCallback listener) {
    _notifier.removeListener(listener);
  }

  @override
  void removeStatusListener(AnimationStatusListener listener) {
    // status will never change.
  }

  @override
  AnimationStatus get status => AnimationStatus.forward;

  @override
  T get value => _transformer.call(_listenable);
}



final _rightAnimation = DerivedAnimation(_pageController, (controller) {
  return controller.page.clamp(0, 1);
});

final _X = _rightAnimation.animate(Tween());


final _leftAnimation = DerivedAnimation(_pageController, (controller) {
  return controller.page.clamp(0, 1);
});

final _Y = _leftAnimation.animate(Tween());

```

2024-02-22 13:20 UTC, Robbendebiene commented
This currently suffers from a problem where scaling and dragging interfere.

For reference:
- https://github.com/flutter/flutter/issues/137189
- https://github.com/flutter/flutter/issues/68594
- https://github.com/flutter/flutter/issues/65006

2024-02-26 10:07 UTC, Robbendebiene commented on lib/widgets/gallery_viewer.dart
> +}
Please move this to the widgets directory as `derived_animation.dart`

Ideally add a short doc comment (`/// this is a doc comment`) to the class

2024-02-26 10:10 UTC, Robbendebiene commented on lib/widgets/gallery_viewer.dart
> +                  fit: BoxFit.contain,
(nit) missing indentation

2024-02-26 10:10 UTC, Robbendebiene commented on lib/widgets/gallery_viewer.dart
> +                (context, index) {
(nit) move this line to the previous line

2024-02-28 09:31 UTC, merged