Implementation marker upload animation
OPENER-next/OpenStop pull request #250
Opened 2024-03-14 14:12 UTC by yulieth9109

2024-04-15 10:43 UTC, Robbendebiene requested changes
I added one more TODO in the code.

Also we should probably dispose the generated image in the widgets dispose method or whenever we create a new one in didUpdateWidget.

2024-04-15 10:43 UTC, Robbendebiene commented on lib/widgets/osm_element_layer/upload_animation.dart
> +    });
Please adjust the parameters to the following:

```dart
  const UploadAnimation({
    required this.active,
    required this.child,
    this.particleSpeed // type is double
    this.particlesEmitRate // Duration, (previously emitDuration)
    this.particleLanes, // type is int
    this.particleGap, // double
    this.particleOverflow // type is double (will be padding)
    this.particleColor = Colors.white,
    this.particleOffset // type is Offset (previously initialX which was actually used as Y)
    this.particleSize // type Size
    super.key,
  });
```

internally calculate the respective values for newton if needed.

Add doc comments to the parameters/variables.

2024-04-25 08:01 UTC, Robbendebiene requested changes

2024-04-29 16:35 UTC, yulieth9109 commented on lib/widgets/osm_element_layer/upload_animation.dart
> +        _image = image;
I wrote at the end of the function after setting the state, still throws an error since there reference of the image it is pointed to the _image variable

2024-04-29 21:20 UTC, yulieth9109 commented on lib/widgets/osm_element_layer/upload_animation.dart
> +        _newtonKey.currentState?.clearEffects;
I tried it but Newton does not update the effect, then i have to update it in that way

2024-05-03 06:53 UTC, Robbendebiene requested changes

2024-05-03 06:53 UTC, Robbendebiene commented on lib/widgets/osm_element_layer/upload_animation.dart
>          _image = image;
Minor: Since `_initializeEffect` is only used once, remove the function and put the code directly into `initState`

2024-05-03 06:53 UTC, Robbendebiene commented on lib/widgets/osm_element_layer/upload_animation.dart
> +        _image = image;
The previous image should only be disposed in the `didUpdateWidget` function. Since this is currently incorrect (no new image is generated) I suspect this to be the reason for your problem.

2024-05-06 12:45 UTC, yulieth9109 commented on lib/widgets/osm_element_layer/upload_animation.dart
> +        _image = image;
The image will only be generated once since the custom effect resizes it. That is why I do not generate the image again in didUpdateWidget, in that case, the dispose it is only needed in the dispose part of the widget. What are your though regarding it?

2024-05-06 12:46 UTC, yulieth9109 commented on lib/widgets/osm_element_layer/upload_animation.dart
> +    if (widget.active != oldWidget.active || widget.particleColor != oldWidget.particleColor || widget.particleDuration != oldWidget.particleDuration || widget.particleEmitRate != oldWidget.particleE
Could you explain in other words this " widget.active != oldWidget.active || // REMOVE THIS AND widget.active ? _effect.start() : _effect.stop(); AS THIS CASE IS HANDLED IN THE IF STATEMENT BELOW"?  I did not get it.

2024-05-07 07:17 UTC, Robbendebiene commented on lib/widgets/osm_element_layer/upload_animation.dart
> +        _image = image;
My fear is that the resizing can lead to poor (pixelated) results so regenerating the image when the size changes seems safer to me.

2024-05-07 07:22 UTC, Robbendebiene commented on lib/widgets/osm_element_layer/upload_animation.dart
> +    if (widget.active != oldWidget.active || widget.particleColor != oldWidget.particleColor || widget.particleDuration != oldWidget.particleDuration || widget.particleEmitRate != oldWidget.particleE
You are already checking whether the `active` property changes here:

https://github.com/OPENER-next/OpenStop/blob/48c8cb4fa7593df7afdf22dd3ff00541419ad833/lib/widgets/osm_element_layer/upload_animation.dart#L118-L120

So there is no need to check it again.

2024-05-07 10:34 UTC, yulieth9109 commented on lib/widgets/osm_element_layer/upload_animation.dart
>          _image = image;
I did not delete it since I used in the didUpdateWidget

2024-06-06 08:45 UTC, merged