Add elevator questions
OPENER-next/OpenStop pull request #271
Opened 2024-07-01 13:30 UTC by wielandb

This PR adds some questions that relate to the recent "Evelator dimensions" proposal.

These questions are:
- What shape does this elevator have?
- What's the diameter of this elevator?
- How tall is the cabin of this elevator?
- How wide is the door of this elevator?
- How tall is the door of this elevator?

It modifies the questions
- How wide is this elevator?
- How deep is this elevator?
to only be asked if the elevator has a rectangular shape

2024-07-03 09:06 UTC, 7h30n3 requested changes

2024-07-03 09:06 UTC, 7h30n3 commented on assets/question_catalog/locales/en.arb
> +  "elevatorDoorWidthText": "How wide is the door of this elevator?",
To be more in line with existing questions: "What is the width of the elevator door?

2024-07-03 09:06 UTC, 7h30n3 commented on assets/question_catalog/locales/en.arb
> +  "elevatorDoorHeightText": "How tall is the door of this elevator?",
To be more in line with existing questions: "What is the height of the elevator door?"

2024-07-03 09:06 UTC, 7h30n3 commented on assets/question_catalog/locales/en.arb
> +  "elevatorDoorHeightPlaceholder": "Clearance in meters",
Just "Height".

2024-07-08 13:57 UTC, Robbendebiene requested changes

2024-07-08 13:57 UTC, Robbendebiene commented on assets/question_catalog/definition.json
> +   },
For the first PR please omit the circular elevator case.
I'm not sure if we really want this in OpenStop due to the requirement of the `shape=rectangular` tag.

2024-07-08 13:57 UTC, Robbendebiene commented on assets/question_catalog/definition.json
> +            "min": 1,
How about 1.5m / 150cm?

2024-07-08 13:57 UTC, Robbendebiene commented on assets/question_catalog/definition.json
> +            "unit": "@unitMeter"
The units in the existing elevator question are in centimetres so please align the new questions accordingly.

2024-07-08 13:57 UTC, Robbendebiene commented on assets/question_catalog/definition.json
> +      ]
What is the idea of this? To exclude door nodes PART of an elevator way or door nodes connected to an elevator via a footway?

2024-07-09 10:54 UTC, wielandb commented on assets/question_catalog/definition.json
> +            "min": 1,
Used 1.5

2024-07-09 10:59 UTC, wielandb commented on assets/question_catalog/locales/en.arb
> +  "elevatorShapeCustomOption": "Something else",
Used Complex

2024-07-09 11:14 UTC, wielandb commented on assets/question_catalog/definition.json
> +   },
Could you explain further? What problems could arise?

2024-07-09 11:17 UTC, wielandb commented on assets/question_catalog/definition.json
> +      ]
Connected via footway

2024-07-09 11:23 UTC, wielandb commented
The JSON validation fails.

I don't really understand what's wrong about
```
            "max": 4,
            "unit": "@unitCentimeter"
         },
         "constructor": {
            "diameter": ["CONCAT", "$input", "m"]
         }
      },
```

2024-07-10 08:20 UTC, Robbendebiene requested changes

2024-07-10 08:20 UTC, Robbendebiene commented on assets/question_catalog/locales/en.arb
> +  "elevatorDoorHeightDescription": "This means the inner clearance from the bottom of the door to the top, not the height of the frame"
The clearance height is the inner measurement from the bottom of the door to the top, not the outer height of the door frame.

2024-07-10 08:20 UTC, Robbendebiene commented on assets/question_catalog/locales/en.arb
> +  "elevatorDoorWidthDescription": "This means the inner clearance from one side of the door to the other, not the width of the frame",
The clearance width is the inner measurement from one side of the door to the other, not the outer width of the door frame.

2024-07-10 08:28 UTC, wielandb commented on assets/question_catalog/definition.json
> +   },
- Right, but how do we handle that?
- Do you think resolving https://github.com/OPENER-next/OpenStop/issues/270 would address this?
- I personally think the diameter of a perfectly round elevator is not difficult to measure. o.o

2024-07-10 08:30 UTC, wielandb commented on assets/question_catalog/definition.json
> +   },
There is actually some kind of precedent: You can tag `roof:shape=many` for roofs. 

So, your preferred option would be that we (for now) ignore everything that does not concern rectangular elevators?

2024-07-10 08:31 UTC, wielandb commented on assets/question_catalog/locales/de.arb
> +          }lder": {},
Da heck happend there? 🙈

2024-07-10 11:59 UTC, wielandb commented on assets/question_catalog/definition.json
> +         }
I think I fixed everything now!

2024-07-10 12:50 UTC, wielandb commented on assets/question_catalog/definition.json
> +      ]
Keeping it as it is

2024-07-11 12:02 UTC, Robbendebiene requested changes

2024-07-11 12:02 UTC, Robbendebiene commented on assets/question_catalog/locales/de.arb
> +  "elevatorDoorWidthDescription": "Gemeint ist die lichte Breite der Tür, also die Breite der Türöffnung, nicht die Breite des Türrahmens.",
Please adjust according to the English translation.

2024-07-11 12:02 UTC, Robbendebiene commented on assets/question_catalog/locales/de.arb
> +  "elevatorDoorHeightDescription": "Gemeint ist die lichte Höhe der Tür, also die Höhe der Türöffnung, nicht die Höhe des Türrahmens.",
Please adjust according to the English translation.

2024-07-11 12:02 UTC, Robbendebiene commented on assets/question_catalog/locales/en.arb
> +  "@elevatorShapeCustomOption": {},
Can be removed

2024-07-16 06:18 UTC, Robbendebiene requested changes

2024-07-16 06:18 UTC, Robbendebiene commented on assets/question_catalog/definition.json
> +                     }
The conditions for the elevator door height are a little tighter which I prefer. Please use the same conditions for the door width.

2024-07-16 06:18 UTC, Robbendebiene commented on assets/question_catalog/definition.json
> +      ],
Shouldn't we have `"osm_element": "Node"` as an additional condition for both questions?

2024-07-16 06:18 UTC, Robbendebiene commented on assets/question_catalog/definition.json
> +      "$comment": "The condition is trying to make sure that there is no separately mapped elevator door by excluding the question if another door with elevator-door-like properties is on the same fo
Please also copy/paste the comment to the door width question.

2024-07-17 12:12 UTC, Robbendebiene commented on assets/question_catalog/definition.json
> +      ],
We decided to ask this question for Nodes AND ClosedWays but add an additional condition for the ClosedWay case to check whether a door node is already a child of the elevator.

2024-07-19 07:59 UTC, Robbendebiene requested changes
Move all new elevator questions right below the elevator width/length questions.

2024-07-19 07:59 UTC, Robbendebiene commented on assets/question_catalog/definition.json
> +                "osm_element": ["OpenWay", "ClosedWay"],
I think it makes sense to only look for an `OpenWay` here.

```suggestion
                "osm_element": "OpenWay",
```

2024-07-19 07:59 UTC, Robbendebiene commented on assets/question_catalog/definition.json
> +                "osm_element": ["OpenWay", "ClosedWay"],
I think it makes sense to only look for an `OpenWay` here.

```suggestion
                "osm_element": "OpenWay",
```

2024-07-22 08:49 UTC, merged