Add open questions
OPENER-next/OpenStop pull request #272
Opened 2024-07-01 16:42 UTC by wielandb

This PR adds questions regarding the recent `open=` proposal.

Theese questions are:
- Is this door normally open?
- How wide is the opening in this partially open door?

2024-07-03 11:51 UTC, 7h30n3 requested changes

2024-07-03 11:51 UTC, 7h30n3 commented on assets/question_catalog/locales/de.arb
> +  "doorOpeningDescription": "Gemeint ist die lichte Breite, die zur Verfügung steht, wenn die Tür zu dem grad geöffnet ist, wie sie es normalerweise ist.",
Please rephrase this sentence, especially the last part is phrased quite complicatly and add why this is important to record.

2024-07-03 11:51 UTC, 7h30n3 commented on assets/question_catalog/locales/de.arb
> +  "doorOpeningPlaceholder": "Breite",
"Durchgangsbreite"

2024-07-03 11:51 UTC, 7h30n3 commented on assets/question_catalog/locales/en.arb
> +  "doorOpenName": "Door permanently open status",
"Door usually open" and for the follow-up question: "Door opening".

2024-07-03 11:51 UTC, 7h30n3 commented on assets/question_catalog/locales/en.arb
> +  "doorOpenText": "Is the door permanently open?",
permanently > usually

2024-07-03 11:51 UTC, 7h30n3 commented on assets/question_catalog/locales/en.arb
> +  "doorOpeningText": "What is the width of the open part of the door?",
"What is the clearance width of the partially open door?"

2024-07-03 11:51 UTC, 7h30n3 commented on assets/question_catalog/locales/en.arb
> +  "doorOpeningPlaceholder": "Width",
Clearance width

2024-07-09 13:51 UTC, wielandb commented on assets/question_catalog/definition.json
> +               "level": true,
Other door questions have this as a prerequisite. So I thought this question should too.

2024-07-09 14:02 UTC, wielandb commented
> I also think the tag doesn't make much sense for sliding doors. So they should be excluded as well.

Really? One of our examples in the proposal is a sliding door.

2024-07-10 07:30 UTC, Robbendebiene requested changes

2024-07-10 07:30 UTC, Robbendebiene commented on assets/question_catalog/locales/de.arb
> +  "doorOpeningName": "Breite der Türöffnung",
Durchgangsbreite der Türöffnung

2024-07-10 07:30 UTC, Robbendebiene commented on assets/question_catalog/locales/en.arb
> +  "doorOpeningDegreeText": "How wide open is the door?",
Not sure if this is correct.
"How wide is the door open?" sounds more common to me.

2024-07-10 07:30 UTC, Robbendebiene commented on assets/question_catalog/locales/en.arb
> +  "doorOpeningText": "What is the clearance width of the partially open door?",
How wide is the opening of the partially open door?

2024-07-10 07:30 UTC, Robbendebiene commented on assets/question_catalog/locales/en.arb
> +  "doorOpeningDescription": "This means the width that is unobstructed when the door as opened to the degree it usually is.",
The extent (clearance width) to which the door is currently open.

2024-07-10 08:15 UTC, wielandb commented on assets/question_catalog/definition.json
> +               "level": true,
So should it be kept?

2024-07-10 08:17 UTC, wielandb commented on assets/question_catalog/definition.json
> +               "image": "assets/question_catalog/images/door_open_no.jpg",
I think images would be helpful, so I would simply change the question to be a list question.

2024-07-11 08:48 UTC, wielandb commented on assets/question_catalog/definition.json
> +               "image": "assets/question_catalog/images/door_open_no.jpg",
Combined two questions back into one

2024-07-11 08:49 UTC, wielandb commented
Ready for re-review now, schematic images are to be added later.

2024-07-11 11:48 UTC, Robbendebiene requested changes

2024-07-11 11:48 UTC, Robbendebiene commented on assets/question_catalog/locales/de.arb
> +  "doorOpenName": "Tür gewöhnlich offen",
"Offene Tür"

2024-07-11 11:48 UTC, Robbendebiene commented on assets/question_catalog/locales/en.arb
> +  "doorOpenName": "Door usually open",
"Open door"

2024-07-11 11:48 UTC, Robbendebiene commented on assets/question_catalog/locales/en.arb
> +  "doorOpenDescription": "This is important so that wheelchair users know if they need to open a door or if they can just pass through. The question should be skipped if it is hard to assess.",
minor: "...know if they need to open **the** door..."

2024-07-11 11:48 UTC, Robbendebiene commented on assets/question_catalog/locales/en.arb
> +  "@doorOpeningDegreeText": {},
Can be removed

2024-07-11 11:48 UTC, Robbendebiene commented on assets/question_catalog/locales/de.arb
> +  "@doorOpeningDegreeText": {},
Can be removed

2024-07-11 11:48 UTC, Robbendebiene commented on assets/question_catalog/locales/de.arb
> +  "doorOpeningDescription": "Gemeint ist die lichte Breite, wenn die Tür in ihrer üblichen Position geöffnet ist. Dies ist wichtig, damit Rollstuhlfahrende wissen, ob sie hindurch passen.",
Use translation of the english version: "Das Ausmaß (lichte Breite) um welches die Tür derzeit geöffnet ist."

2024-07-11 11:48 UTC, Robbendebiene commented on assets/question_catalog/locales/de.arb
> +  "@doorOpenYesOption": {},
Can be removed

2024-07-11 11:48 UTC, Robbendebiene commented on assets/question_catalog/locales/en.arb
> +  "@doorOpenYesOption": {},
Can be removed

2024-07-11 11:48 UTC, Robbendebiene commented on assets/question_catalog/definition.json
> +      },
Minor: change order to "no, partial, full" to avoid users missing the partial option and therefore selecting full.

2024-07-11 11:48 UTC, Robbendebiene commented on assets/question_catalog/definition.json
> +         }
Still wrong. Please exercise more care.

2024-07-15 07:35 UTC, wielandb commented
Should be ready for re-review now

2024-07-16 06:26 UTC, Robbendebiene commented on assets/question_catalog/definition.json
> +         }
It's not just the min, max units. The constructor also needs to be adjusted.

2024-07-17 07:15 UTC, Robbendebiene requested changes

2024-07-17 07:15 UTC, Robbendebiene commented on assets/question_catalog/definition.json
> +
Remove empty line and also `"automatic_door": "continuous"`, because open partial makes limited to no sense to a revolving door in general. (remember to do it for **all** the affected conditions)

2024-07-17 07:15 UTC, Robbendebiene commented on assets/question_catalog/locales/de.arb
> +  "@doorOpeningName": {},
These keys are missing now in the english language file.

2024-07-18 13:42 UTC, Robbendebiene approved these changes
LGTM 🚪

2024-07-18 13:43 UTC, merged