Split footway map feature into more detailed features
OPENER-next/OpenStop pull request #300
Opened 2024-12-03 08:03 UTC by Robbendebiene

Implements #298 
 
- Also adds a combined foot- & cycle path crossing map feature
- Introduces map feature priorities and removes the map feature score. Both systems help to decide which map feature should take precedence when multiple match the same element.
- Minor fixes

2024-12-03 11:14 UTC, 7h30n3 requested changes

2024-12-03 11:14 UTC, 7h30n3 commented on lib/l10n/app_en.arb
> +  "mapFeatureFootAndCyclePath": "Foot & cycle path",
I'm unsure about using an ampersand here. This would be the first time. Although I like the approach of keeping it short, I prefer using a proper "and".

2024-12-03 11:23 UTC, Robbendebiene commented on lib/models/map_features/map_features.dart
> +    label: (locale, _) => locale.mapFeatureCrossing,
This is intentional as they both describe an (unspecific) crossing. You got a point though since we could merge these two map features into one. I didn't merge them because from a technical standpoint they are different (differ in tags & element type). I could have also introduced the label "Foot & cycle crossing" for the new map feature. I don't have a preference here, so let me know what you prefer.

2024-12-03 11:27 UTC, Robbendebiene commented on lib/l10n/app_en.arb
> +  "mapFeatureFootAndCyclePath": "Foot & cycle path",
I tend to keep it in order to keep it short. It was also sort of suggested in the respective issue.

>     Main question is how do we name the combination of foot- and cycleway?
> 
> I suggest Cycle & Foot Path, as iD calls them.

Do we have any map features where we use "and"? We could align them if you want.

2024-12-03 12:18 UTC, 7h30n3 commented on lib/models/map_features/map_features.dart
> +    label: (locale, _) => locale.mapFeatureCrossing,
Let's go with your guts and do it like you initially intend it. So, let's keep everything the way it is.

2024-12-03 12:19 UTC, 7h30n3 commented on lib/l10n/app_en.arb
> +  "mapFeatureFootAndCyclePath": "Foot & cycle path",
Okay, then let's keep the ampersand.

2024-12-03 15:15 UTC, 7h30n3 approved these changes

2024-12-09 14:29 UTC, 7h30n3 approved these changes

2024-12-09 14:33 UTC, merged