Remove questions about ways
OPENER-next/OpenStop pull request #91
Opened 2022-08-10 09:22 UTC by 7h30n3

..,because there are too many of them.

2022-08-12 11:47 UTC, Robbendebiene requested changes

2022-08-12 11:47 UTC, Robbendebiene commented on assets/datasets/question_catalog.json
> -      ]
We can keep this.

2022-08-12 11:47 UTC, Robbendebiene commented on assets/datasets/question_catalog.json
> -   },
We should keep this. If not all then at least the `"public_transport": "platform",` part.

2022-08-15 08:02 UTC, 7h30n3 commented on assets/datasets/question_catalog.json
> -      ]
Re-added.

2022-08-15 08:02 UTC, 7h30n3 commented on assets/datasets/question_catalog.json
> -   },
Re-added the `platform`-Part.

2022-08-16 07:45 UTC, Robbendebiene approved these changes
LGTM

2022-08-16 08:21 UTC, merged