Assign one map feature to multiple osm_tags or osm_elements
OPENER-next/OpenStop pull request #92
Opened 2022-08-11 07:39 UTC by 7h30n3

2022-08-12 11:31 UTC, Robbendebiene commented on assets/datasets/map_feature_collection.json
> +      "sidewalk": true
In theory also `sidewalk:right`, `sidewalk:left`, `sidewalk:both` should be checked. This would require 3 new elements since we do not allow the same type of "OR" conditions as we do in the question catalog.

Currently we also do not have an icon for:
- elevator
- escalator

Maybe this should be done in a separate PR?

2022-08-12 11:31 UTC, Robbendebiene commented on test/osm_upload_api_test.dart
>        ),
What's the purpose of this change? It feels like `mapFeatureCollection[...].osmTags[0]` would always return null since there is no tag `0`.

2022-08-15 09:19 UTC, 7h30n3 commented on test/osm_upload_api_test.dart
>        ),
Thanks for the hint. That was just a quick and dirty solution on my part. I forgot to properly adapt this. 
But now it should be.

2022-08-17 08:39 UTC, 7h30n3 commented on assets/datasets/map_feature_collection.json
> +      "sidewalk": true
Resolved in 31f65b66daf57387f9e51bdc59eda8c931cd22ca and 4ef0f2e

2022-08-17 10:39 UTC, Robbendebiene requested changes

2022-08-17 10:39 UTC, Robbendebiene commented on assets/datasets/map_feature_collection_schema.json
> +        "minItems": 1
In json schemas it is possible to include other schema files. Since we now share a big portion of the schema with the question schema I think it would make sense to outsource this in a separate file which is then included in both schemas

2022-08-17 10:39 UTC, Robbendebiene commented on lib/models/map_feature.dart
> +
Can be removed

2022-08-17 10:39 UTC, Robbendebiene commented on lib/models/osm_condition.dart
Multiple unnecessary changes

2022-08-17 10:39 UTC, Robbendebiene commented on lib/models/map_feature_collection.dart
> +        final newScore = mapFeature.conditions.length;
This doesn't resemble the same criteria as before.

Previously the more tags were matched the higher was the score. Now the more conditions a map feature has the higher is its score. 

I would go for something like this:

```dart
try {
     final matchingCondition = mapFeature.conditions.firstWhere((condition) {
        return condition.matches(
            osmElement.tags,
            typeFromOSMElement(osmElement)
        );
      });
      // check if there already exists an answer with the same question
      final newScore = matchingCondition.osmTags.length;
       if (newScore > score) {
          score = newScore;
          bestMatch = mapFeature;
        }
}
on StateError {}
```

Btw this comment `// check if there already exists an answer with the same question` doesn't seem to make sense (anymore?)

2022-08-17 10:39 UTC, Robbendebiene commented on test/osm_upload_api_test.dart
>        osmapi.createElement(
all `conditions[x]` should have x = 0.
Maybe write `conditions.first`instead.

2022-08-17 10:39 UTC, Robbendebiene commented on test/osm_upload_api_test.dart
>          changesetId
`Map.of(mapFeatureCollection[2].conditions.fist.osmTags.cast<String, String>()),`

2022-08-17 11:40 UTC, Robbendebiene commented on assets/datasets/map_feature_collection.json
> +        "osm_element": ["OpenWay", "ClosedWay"]
The sidewalk values need to be changed.

"yes" for sidewalk:SIDE
and "yes", "right", "both", "left" for the normal sidealk tag

2022-08-17 11:42 UTC, 7h30n3 commented on lib/models/map_feature.dart
> +
Thanks.

2022-08-17 13:16 UTC, Robbendebiene commented on lib/models/osm_condition.dart
>    bool matchesElement(OSMElementType type) =>
I'm still in favour of reverting this. At least the comments should be adjusted

2022-08-17 13:16 UTC, Robbendebiene commented on lib/models/map_feature_collection.dart
> +        // check if there already exists a matched map feature
nit picky but I would either remove the comment or make it more descriptive `// check if the newly matched map feature has more matching tags than the previously matched map feature`

2022-08-17 13:16 UTC, Robbendebiene commented on assets/datasets/osm_condition_schema.json
> +}
No new line

2022-08-17 13:16 UTC, Robbendebiene commented
JSON validation failed

2022-08-18 07:45 UTC, merged